version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty

    working_directory: ~/repo

    steps:
      - run: echo 'export PATH=/opt/qt59/bin/:$PATH' >> $BASH_ENV
      - run: echo 'export QTDIR=/opt/qt59' >> $BASH_ENV
      - run: echo 'export LD_LIBRARY_PATH=/opt/qt59/lib/x86_64-linux-gnu:/opt/qt59/lib:$LD_LIBRARY_PATH' >> $BASH_ENV
      - run: echo 'export PKG_CONFIG_PATH=/opt/qt59/lib/pkgconfig:$PKG_CONFIG_PATH' >> $BASH_ENV

      - checkout

      # Clang-format sources check
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y clang-format-3.8
          sudo ln -s /usr/bin/clang-format-3.8 /usr/bin/clang-format
          SOURCE_FILES=`find ./ReactQt/ -name \*.cpp -type f -or -name \*.h -type f`
          for SOURCE_FILE in $SOURCE_FILES
          do
            export FORMATTING_ISSUE_COUNT=`clang-format -output-replacements-xml $SOURCE_FILE | grep offset | wc -l`
            if [ "$FORMATTING_ISSUE_COUNT" -gt "0" ]; then
              echo "Source file $SOURCE_FILE contains formatting issues. Please use clang-format tool to resolve found issues."
              exit 1
            fi
          done

      # Install and configure env with Qt
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:beineri/opt-qt591-trusty
          sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
          sudo apt-get -qy update
          sudo apt-get install -y dbus xvfb curl cmake mesa-common-dev \
              qt59base qt59graphicaleffects qt59quickcontrols2 qt59declarative qt59websockets
          echo "/opt/qt59/bin/qt59-env.sh" >> ~/.circlerc

      # Install node
      - run: |
          curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
          sudo apt-get install -y nodejs

      - run: |
          cmake -version
          qmake -version

      # Repair dbus
      - run: ln -s /var/lib/dbus/machine-id /etc/machine-id

      # Build react-native-desktop in Debug (RCT_DEV enabled)
      - run: |
          mkdir build_debug
          pushd build_debug
          cmake -DCMAKE_BUILD_TYPE=Debug .. && make -j4
          popd

      # Build react-native-desktop in Release
      - run: |
          mkdir build
          pushd build
          cmake -DCMAKE_BUILD_TYPE=Release .. && make -j4
          popd

      # Download and cache dependencies
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run: |
          rm -rf ./node_modules/metro
          npm install

      # Apply metro patch to add desktop platform
      - run: patch --verbose -d ./node_modules/metro/src -i ../../../add-desktop-platform.patch

      - type: shell
        name: Start packager
        command: npm start
        background: true

      - type: shell
        name: Start ubuntu-server.js
        command: node ./ubuntu-server.js
        background: true

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

      # run tests!
      - run: npm test

      # run unit tests
      - run: |
          pushd build
          xvfb-run --server-args="-screen 0 1024x768x24" ctest -VV
          popd
